[tools]
erlang = "28"
gleam = "1.12.0"

[tasks.dev]
dir = "spectator"
env = { ERL_FLAGS = "-sname spectator" }
run = 'watchexec --restart --verbose --wrap-process=session --stop-signal SIGTERM --exts gleam --debounce 500ms --watch src/ -- "gleam run -m playground"'

[tasks.test]
dir = "spectator"
run = 'gleam test'

[tasks."build:escript"]
dir = "spectator_app"
run = [
  'gleam build',
  'gleam run -m gleescript'
]
[tasks."build:docker"]
run = 'docker build . -t spectator'

[tasks."run:docker"]
run = 'docker run --rm --hostname spectator -p 3000:3000 spectator'