name = "spectator"
version = "1.4.3"
description = "BEAM observer tool"
licences = ["MIT"]
repository = { type = "github", user = "JonasGruenwald", repo = "spectator" }

[dependencies]
simplifile = ">= 2.2.0 and < 3.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
mist = ">= 5.0.3 and < 6.0.0"
gleam_stdlib = ">= 0.65.0 and < 1.0.0"
lustre = ">= 5.3.5 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
carpenter = { path = "packages/carpenter" }
