name = "spectator"
version = "1.3.1"
description = "BEAM observer tool"
licences = ["MIT"]
repository = { type = "github", user = "JonasGruenwald", repo = "spectator" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.27.0 and < 1.0.0"
gleam_otp = ">= 0.12.1 and < 1.0.0"
lustre = ">= 4.5.1 and < 5.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
mist = ">= 3.0.0 and < 4.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
chrobot = ">= 3.0.1 and < 4.0.0"
